function Test2AlgorithmPrepareRun(a1p, a1r, a2p, a2r, xlim, xtick, ttl, xlbl, ylbl, a1name, a2name)
plot(xtick, a1p, 'ro:', ...
     xtick, a2p, 'bs:', ...
     xtick, a1r, 'r+-', ...
     xtick, a2r, 'b*-');
set(gca, 'XLim', xlim);
set(gca, 'XTick', xtick);
set(gca, 'YGrid', 'on');
title(ttl);
xlabel(xlbl);
ylabel(ylbl);
legend(strcat(a1name, ' (Preparing)'), ...
       strcat(a2name, ' (Preparing)'), ...
       strcat(a1name, ' (Compute)'), ...
       strcat(a2name, ' (Compute)'), ...
       'Location', 'NorthWest')
end